/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DeFiEsusuInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PENALTY_BASIS_POINTS"
      | "circles"
      | "contributeToCircle"
      | "createCircle"
      | "depositPersonal"
      | "feeCollector"
      | "getCircleDetails"
      | "joinCircle"
      | "nextCircleId"
      | "personalVaults"
      | "usdcToken"
      | "withdrawPersonal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircleCreated"
      | "CirclePayout"
      | "CircleStarted"
      | "ContributionMade"
      | "MemberJoined"
      | "PersonalDeposit"
      | "PersonalWithdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PENALTY_BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeToCircle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCircle",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPersonal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCircleDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinCircle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCircleId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "personalVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPersonal",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PENALTY_BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "circles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributeToCircle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCircle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPersonal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCircleDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinCircle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCircleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "personalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPersonal",
    data: BytesLike
  ): Result;
}

export namespace CircleCreatedEvent {
  export type InputTuple = [
    circleId: BigNumberish,
    amount: BigNumberish,
    maxMembers: BigNumberish
  ];
  export type OutputTuple = [
    circleId: bigint,
    amount: bigint,
    maxMembers: bigint
  ];
  export interface OutputObject {
    circleId: bigint;
    amount: bigint;
    maxMembers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CirclePayoutEvent {
  export type InputTuple = [
    circleId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    circleId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    circleId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CircleStartedEvent {
  export type InputTuple = [circleId: BigNumberish];
  export type OutputTuple = [circleId: bigint];
  export interface OutputObject {
    circleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [
    circleId: BigNumberish,
    contributor: AddressLike,
    round: BigNumberish
  ];
  export type OutputTuple = [
    circleId: bigint,
    contributor: string,
    round: bigint
  ];
  export interface OutputObject {
    circleId: bigint;
    contributor: string;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [
    circleId: BigNumberish,
    member: AddressLike,
    currentCount: BigNumberish
  ];
  export type OutputTuple = [
    circleId: bigint,
    member: string,
    currentCount: bigint
  ];
  export interface OutputObject {
    circleId: bigint;
    member: string;
    currentCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalDepositEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, unlockTime: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalWithdrawalEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, penalty: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeFiEsusu extends BaseContract {
  connect(runner?: ContractRunner | null): DeFiEsusu;
  waitForDeployment(): Promise<this>;

  interface: DeFiEsusuInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PENALTY_BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  circles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        contributionAmount: bigint;
        maxMembers: bigint;
        currentRound: bigint;
        isActive: boolean;
        roundBalance: bigint;
      }
    ],
    "view"
  >;

  contributeToCircle: TypedContractMethod<
    [_circleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCircle: TypedContractMethod<
    [_amount: BigNumberish, _maxMembers: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositPersonal: TypedContractMethod<
    [_amount: BigNumberish, _lockDurationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getCircleDetails: TypedContractMethod<
    [_circleId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        amount: bigint;
        max: bigint;
        currentCount: bigint;
        active: boolean;
        round: bigint;
      }
    ],
    "view"
  >;

  joinCircle: TypedContractMethod<
    [_circleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextCircleId: TypedContractMethod<[], [bigint], "view">;

  personalVaults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        balance: bigint;
        unlockTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  withdrawPersonal: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PENALTY_BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "circles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        contributionAmount: bigint;
        maxMembers: bigint;
        currentRound: bigint;
        isActive: boolean;
        roundBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributeToCircle"
  ): TypedContractMethod<[_circleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCircle"
  ): TypedContractMethod<
    [_amount: BigNumberish, _maxMembers: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositPersonal"
  ): TypedContractMethod<
    [_amount: BigNumberish, _lockDurationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCircleDetails"
  ): TypedContractMethod<
    [_circleId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        amount: bigint;
        max: bigint;
        currentCount: bigint;
        active: boolean;
        round: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinCircle"
  ): TypedContractMethod<[_circleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextCircleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "personalVaults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        balance: bigint;
        unlockTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawPersonal"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CircleCreated"
  ): TypedContractEvent<
    CircleCreatedEvent.InputTuple,
    CircleCreatedEvent.OutputTuple,
    CircleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CirclePayout"
  ): TypedContractEvent<
    CirclePayoutEvent.InputTuple,
    CirclePayoutEvent.OutputTuple,
    CirclePayoutEvent.OutputObject
  >;
  getEvent(
    key: "CircleStarted"
  ): TypedContractEvent<
    CircleStartedEvent.InputTuple,
    CircleStartedEvent.OutputTuple,
    CircleStartedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PersonalDeposit"
  ): TypedContractEvent<
    PersonalDepositEvent.InputTuple,
    PersonalDepositEvent.OutputTuple,
    PersonalDepositEvent.OutputObject
  >;
  getEvent(
    key: "PersonalWithdrawal"
  ): TypedContractEvent<
    PersonalWithdrawalEvent.InputTuple,
    PersonalWithdrawalEvent.OutputTuple,
    PersonalWithdrawalEvent.OutputObject
  >;

  filters: {
    "CircleCreated(uint256,uint256,uint256)": TypedContractEvent<
      CircleCreatedEvent.InputTuple,
      CircleCreatedEvent.OutputTuple,
      CircleCreatedEvent.OutputObject
    >;
    CircleCreated: TypedContractEvent<
      CircleCreatedEvent.InputTuple,
      CircleCreatedEvent.OutputTuple,
      CircleCreatedEvent.OutputObject
    >;

    "CirclePayout(uint256,address,uint256)": TypedContractEvent<
      CirclePayoutEvent.InputTuple,
      CirclePayoutEvent.OutputTuple,
      CirclePayoutEvent.OutputObject
    >;
    CirclePayout: TypedContractEvent<
      CirclePayoutEvent.InputTuple,
      CirclePayoutEvent.OutputTuple,
      CirclePayoutEvent.OutputObject
    >;

    "CircleStarted(uint256)": TypedContractEvent<
      CircleStartedEvent.InputTuple,
      CircleStartedEvent.OutputTuple,
      CircleStartedEvent.OutputObject
    >;
    CircleStarted: TypedContractEvent<
      CircleStartedEvent.InputTuple,
      CircleStartedEvent.OutputTuple,
      CircleStartedEvent.OutputObject
    >;

    "ContributionMade(uint256,address,uint256)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "MemberJoined(uint256,address,uint256)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "PersonalDeposit(address,uint256,uint256)": TypedContractEvent<
      PersonalDepositEvent.InputTuple,
      PersonalDepositEvent.OutputTuple,
      PersonalDepositEvent.OutputObject
    >;
    PersonalDeposit: TypedContractEvent<
      PersonalDepositEvent.InputTuple,
      PersonalDepositEvent.OutputTuple,
      PersonalDepositEvent.OutputObject
    >;

    "PersonalWithdrawal(address,uint256,uint256)": TypedContractEvent<
      PersonalWithdrawalEvent.InputTuple,
      PersonalWithdrawalEvent.OutputTuple,
      PersonalWithdrawalEvent.OutputObject
    >;
    PersonalWithdrawal: TypedContractEvent<
      PersonalWithdrawalEvent.InputTuple,
      PersonalWithdrawalEvent.OutputTuple,
      PersonalWithdrawalEvent.OutputObject
    >;
  };
}
